### ISSUE TITLE
Atom or RSS support?

### ISSUE THREAD

**Issue by jsoo1** [fosskers/servant-xml#5]
Hi there, I was going to make a package to support Atom/RSS feeds and it would be very close to your implementation. (https://github.com/jsoo1/servant-feed). Would you be interested in providing support for it in the xml library instead?

**Comment by fosskers** [comment]
My library *almost* doesn't exist, it's mostly plugging `servant` and `xmlbf` together. Perhaps your library could piggyback on both `xmlbf` and `servant-xml`?

**Comment by jsoo1** [comment]
So I have a fairly simple question. Can I specify a different content-type for XML? I think that would be all I need

**Comment by fosskers** [comment]
```haskell
data XML

instance Accept XML where
  contentType _ = "application" M.// "xml" M./: ("charset", "utf-8")

instance ToXml a => MimeRender XML a where
  mimeRender _ = toLazyByteString . encode . toXml

instance FromXml a => MimeUnrender XML a where
  mimeUnrender _ bs = fromRawXml (toStrict bs) >>= runParser fromXml
```
The whole point of `servant-xml` is to provide the content-type, so there's not much to change :)

And does it need to be different? On my personal website, I serve an RSS endpoint, passing a `Xmlbf` type through this function:

```haskell
xml :: ToXml a => a -> Response
xml = responseLBS status200 headers . toLazyByteString . encode . toXml
  where
    headers = [("Content-Type", "application/xml")]
```
You'll notice the content type is `application/xml`, and that works. I actually no longer use `servant-xml` personally.

**Comment by jsoo1** [comment]
Hmm. I think the plain content type works but I read somewhere the spec was to have `+atom` or `+rss` as a suffix.  Maybe I will just use `servant-xml` to keep it simple, though.

**Comment by jsoo1** [comment]
Also I think this can be closed. Thanks again, question answered.
